### ISSUE TITLE
For() /regex/.test() results in a parse error

### ISSUE THREAD

**Issue by cheako** [svaarala/duktape#1901] opened 2018-04-29 20:50 UTC
```
cheako@debian:~/src/github/cheako-vulkan/014duktape$ ./forregex_test 
b[c]=3=3
DukFatal: uncaught: 'parse error (line 4)'
cheako@debian:~/src/github/cheako-vulkan/014duktape$ cat forregex_test.c 
#include <stdio.h>
#include <assert.h>
#include <duktape.h>

void fatal_function(void *udata, const char *msg) {
	fprintf(stderr, "DukFatal: %s\n", msg);
	exit(1);
}

duk_context *ctx;
static inline void create_heap() {
	ctx = duk_create_heap(NULL, NULL, NULL, NULL, fatal_function);
	assert(ctx && "duk_create_heap_default: Failed.");
}

int main(int argc, char *argv[]) {
  create_heap();
  duk_eval_string(ctx, 
		  "var b = {};\n"
		  "var t = {a: 1, b: 2, c: 3};\n"
		  "for (c in t) (/^b$/).test(c + t[c]) ||\n"
		  "(b[c] = t[c]); b[c];");
  printf("b[c]=3=%d\n", (int) duk_get_int(ctx, -1));
  duk_eval_string(ctx, 
		  "var b = {};\n"
		  "var t = {a: 1, b: 2, c: 3};\n"
		  "for (c in t) \n /^b$/.test(c + t[c]) ||\n"
		  "(b[c] = t[c]); b[c];");
  printf("b[c]=3=%d\n", (int) duk_get_int(ctx, -1));
  duk_eval_string(ctx, 
		  "var b = {};\n"
		  "var t = {a: 1, b: 2, c: 3};\n"
		  "for (c in t) /^b$/.test(c + t[c]) ||\n"
		  "(b[c] = t[c]); b[c];");
  printf("b[c]=3=%d\n", (int) duk_get_int(ctx, -1));
  duk_destroy_heap(ctx);
  return 0;
}
```

**Comment by svaarala** [comment] 2018-05-06 14:53
I'll try to reproduce this with C code but cannot easily reproduce with Ecmascript code:
```

**Comment by svaarala** [comment] 2018-05-06 14:56
Hmm, this seems to be something fixed in master after 2.2.0: master seems to work, 2.2.0 fails; probably this one:
> Fix some lexer bugs related to parsing in RegExp mode (interpret leading '/' as part of a RegExp) or not (interpret '/' as division) (GH-1779)

**Comment by svaarala** [comment] 2018-05-06 14:56
It would be nice if you could retry from master, to see that it indeed fixes your issue too.

**Comment by cheako** [comment] 2018-05-06 16:01
I can try that.

**Comment by svaarala** [comment] 2018-05-15 13:16
@cheako Did you have time to test in master?

**Comment by svaarala** [comment] 2018-05-19 07:53
@cheako Because the specific example works in master I'll close this now. If you have time to re-test in master and find out there are still issues, we can reopen this.

**Closed by svaarala** 2018-05-19 07:53 UTC
