### ISSUE TITLE
require id resolution seems broken for submodules

### ISSUE THREAD

**Issue by amol-** [svaarala/duktape#675] opened 2016-04-10 21:44 UTC
I downloaded https://registry.npmjs.org/react/-/react-0.14.8.tgz and tried to import:

```
require('react')
```

my own `modSearch` was called and prints out what it is looking for:
```
Looking for react 
```
then `react.js` has a `require('./lib/React')` instruction inside.

As Duktape resolves the modules ids itself before providing them to `modSearch` I would have expected to receive `react/lib/React` as the resolved module id, as it was `lib/React` inside `react` (declared as a relative require).

Instead I received `lib/React`:
```
Looking for lib/React
```

Which seems to point that duktape doesn't properly resolve module ids when they are required from within another module.

**Comment by fatcerberus** [comment] 2016-04-10 22:20
This is actually correct.  The last term is the module name, the rest is the path to it.  A relative path is relative to the location of the calling module.  It's like if you have a file named `/foo/bar/pig.txt` and ask for `./pigfile` relative to that, you will get `/foo/bar/pigfile` and NOT `foo/bar/pig.txt/pigfile`.

**Comment by amol-** [comment] 2016-04-10 22:31
In this case `react` is a directory, as it is a nodejs package. `require('react')` resolves to `react/react.js'  so it would make perfectly sense for `./lib/React.js` to resolve to `react/lib/React.js`.

I'm trying to allow requiring nodejs modules in dukpy but I found now way to drive the require id resolver to have the right behaviour (even tried to set `module.name='react/react'` but it seems it's ignored for ids resolution)

**Comment by svaarala** [comment] 2016-04-10 22:31
@amol- Duktape currently resolves module IDs without any knowledge of the actual filename of the current module, and the resolution works in the conceptual CommonJS namespace. In that namespace if a module `foo/bar` requires the name `./quux` it gets interpreted as "load sibling of current module", i.e. `foo/quux`.

This actually used to return `foo/bar/quux` but that was considered incorrect by several users because they would need to use `../quux` to get a sibling which also seems counterintuitive.

For plain files Node.js will behave similarly:

```
$ cat foo.js 
var bar = require('./bar');
console.log(bar.name);
$ cat bar.js 
exports.name = 'B';   // loads sibling foo.js
$ node foo.js
B
```

If a module loader is aware of files and directories it can be more flexible in the ID resolution process. In your case I think what happens is that the initial `require('react')` is resolved to a file `react.js` in a specific directory and relative IDs are then resolved relative to that directory rather than the module ID ("react").

There's a planned change for Duktape 2.x to make the resolution process much more flexible (or make both resolution and loading provided by user code) to allow more flexibility in how resolution is handled.

**Comment by svaarala** [comment] 2016-04-10 22:41
@amol- So in short, currently Duktape resolves IDs purely in the conceptual module namespace and is unaware of files/directories, so it can't be sensitive to where the module has been loaded from in the file system (not all targets even have a filesystem and still use modules). As such the behavior of `.` and `..` are defined within the conceptual namespace only which is unfortunately a bit limiting.

Duktape 2.x will provide more flexibility as mentioned above - but you can also replace `require()` entirely in Duktape 1.x (it's not "magic" in that sense). In fact DukLuv provides a more flexible module loader which is a likely candidate for the Duktape 2.x mechanism:

- The loader is contained in: https://github.com/creationix/dukluv/blob/master/src/main.c
- The `require()` entry point which overwrites the default global `require()` is: https://github.com/creationix/dukluv/blob/master/src/main.c#L154-L245

I'm not sure if that would directly solve your issue, but it splits module loading into `modResolve()` and `modLoad()` for more flexibility. DukLuv is easy to compile and run, so you should be able to test if your scenario works with DukLuv's `require()` provider and use that if it does.

**Comment by svaarala** [comment] 2016-04-10 22:48
@amol- Just to emphasize why this goes wrong for you: once you've said `require('react')`:

- The conceptual module ID is `react`.
- The module was loaded from `/somewhere/react/react.js`.

In resolving the `./lib/React` require:

- Resolving using conceptual identifiers starts from `react` which resolves to `lib/React`.
- Resolving using filenames starts from `/somewhere/react/react.js` which resolves to  `/somewhere/react/lib/React.js`. Note that the `.` is interpreted as a sibling here too, it's just that the starting point is logically different because the original require ID was mapped to `react/react.js`.

If you wanted this to work with the current module resolution process, you could change the file organization a bit and make the first require be `require('react/react')` so that the conceptual name reflected the file system structure. With that `./lib/React` would resolve to `react/lib/React`.

**Comment by amol-** [comment] 2016-04-10 22:51
@svaarala thanks for the example.

I think that a relatively easy solution would be viable for duktape 1.x too without breaking backward compatibility. As in `modSearch` the module itself is available and I'm able to set `filename` and `name` it might be useful to have an additional `id` attribute that I can overwrite when I load a module.

By default the id attribute would match the one resolved by require itself keeping current behaviour but I could override it and tell duktape that `react`  was actually `react/react` which makes everything work as I expect (if I use `require('rect/react')` instead of `require('react')` submodules are correctly resolved)

**Comment by svaarala** [comment] 2016-04-10 22:55
@amol- This was actually covered in an earlier issue: https://github.com/svaarala/duktape/issues/662

In short, you can overwrite the `require.id` of the module being loaded in Duktape.modSearch so that further resolution is based on a different ID. In essence this is module ID aliasing.

**Comment by svaarala** [comment] 2016-04-10 22:58
Here's the root cause in that other issue: https://github.com/svaarala/duktape/issues/662#issuecomment-202918060

In that case `require('foo')` would be mapped to `foo/index.js` which posed a similar issue as yours; the solution there was to overwrite the `require.id` (for the require function passed to modSearch()) from `foo` to `foo/index`.

**Comment by svaarala** [comment] 2016-04-10 23:20
@amol- Relative resolution now works by the fresh require() function given to modSearch() and the module being loaded having an `.id` property giving the resolution base path (rather than the module being looked up and resolution based on that). In hindsight it would've been better for the require function to point to the module object instead which provides `.id` but also other properties potentially useful in resolution. The original design didn't actually cache the module object but only the final export value so that wasn't an option in that design.

This is probably not useful to change significantly in Duktape 1.x: as soon as I'm finished with the 1.5.0 release, master will switch over to Duktape 2.x development and reworking the module handling is one of the first steps there. This is hopefully a couple of months away.

**Comment by fatcerberus** [comment] 2016-05-18 04:25
@svaarala Just to be clear, how does overriding `require.id` in modSearch affect caching?  I've gotten mixed signals here, so I'll come out and ask outright: If e.g. I alias `foo` to `foo/index` by overriding `require.id`, which name will Duktape use for caching purposes?

I ask because I'm going to need Node.js semantics too for minisphere 4.0. ;)

**Comment by saghul** [comment] 2016-05-18 06:39
My observation is that it works. The module is cached and it's not loaded
more than once AFAIS.

**Comment by svaarala** [comment] 2016-05-18 09:26
@fatcerberus The module is registered to Duktape.modLoaded[] with the original resolved ID, before modSearch has been called:

https://github.com/svaarala/duktape/blob/master/src/duk_bi_global.c#L1022-L1028

If you modify the ID in modSearch, the module remains registered with the original resolved ID. This only matters if you:

- Require the module using both the actual CommonJS resolved name and the manually tweaked alias. This should lead to the module being loaded twice.
- Look up the module from Duktape.modLoaded[] yourself manually.

**Comment by saghul** [comment] 2016-05-18 10:00
@svaarala I'm somehow observing something different. In sjs I have an "io" module wich has an index.js. When I require it:

~~~~
sjs> const io = require('io');
aaaaa
= undefined
~~~~

I added a print to see if it was loaded twice. Here is the cache:

~~~~
sjs> Duktape.modLoaded
= {
    io: {},
    errno: {},
    _errno: {},
    _io: {},
    objectutil: {}
}
~~~~

And if I load it again:

~~~~
sjs> const foo = require('io');
= undefined
~~~~

No print!

Here is how I overwrite the id: https://github.com/saghul/sjs/blob/master/src/modules.c#L218-L225

Am I missing something?

**Comment by svaarala** [comment] 2016-05-18 10:16
@saghul You're requiring the module twice using the alias which doesn't lead to a caching issue.

But if you were to require it using:

    require('io');
    require('io/index')

It would resolve to the same source file but conceptually two different modules, one cached using `io`, another using `io/index`. With proper module aliasing there would be only one cache entry and the module would only be loaded once. In other words:

    require(canonicalId) === require(aliasId)

**Comment by saghul** [comment] 2016-05-18 10:19
Ah, I see! Thanks for explaining. I guess it's good enough for me at the moment :-)

**Comment by svaarala** [comment] 2016-05-18 10:21
It should work quite OK if you're only operating with one module ID :) There should be a better solution for aliasing in the near future with Duktape 2.x reworks.

**Comment by fatcerberus** [comment] 2016-05-18 14:19
@svaarala Thanks.  That's what I thought.  One hack that might be possible if this becomes an issue (besides rolling my own `require` of course :) is to manually mess with modLoaded, i.e.

```
Duktape.modLoaded[canonicalID] = Duktape.modLoaded[aliasID];
```

**Comment by svaarala** [comment] 2016-05-18 14:20
Yep, that'd do the trick.

**Comment by fatcerberus** [comment] 2016-05-18 18:00
By the way, it turns out you don't need to use `DUK_DEFPROP_FORCE`, `require.id` is configurable:
https://github.com/svaarala/duktape/blob/master/src/duk_bi_global.c#L998

**Comment by svaarala** [comment] 2016-08-23 20:42
This is no longer a direct Duktape issue because module loading is no longer part of core functionality (it's always provided by the application).

@fatcerberus Do you think `extras/module-node` supports the use case described in the issue? If so, one working solution would be to use the `extras/module-node` loader; it also works in 1.x.

**Comment by fatcerberus** [comment] 2016-08-23 23:26
`module-node` leaves all path resolution up the the application.  The only thing it does for you is to track the post-resolved ID of the module calling `require()`.

So I would say it supports this use case, yes.  In fact it was precisely because of issues like this cropping up all the time that I wrote it. :)

**Closed** 2016-08-24 00:37 UTC
Labels: module, question
