### ISSUE TITLE
CSPROPI target is not a number

### ISSUE THREAD

**Issue by zapolnov** [svaarala/duktape#115] opened 2015-02-06 18:51 UTC
I am trying to execute Microsoft TypeScript compiler (https://github.com/Microsoft/TypeScript/) under the duktape environment.

You can get my test project by the following link:
https://www.dropbox.com/s/49jkz5typ8mwnoc/test.zip?dl=0
The project is cmake-based, but you can just compile both .c files into an executable without any build system.

I have added a dummy implementations for readFile, writeFile, etc. functions and now I am trying just to get it running.

First, I had to make a modification to tsc.js code because duktape erroneously replaced string value of first argument to function createSourceFile with number 268. Adding a fake first argument to this function solved the problem (all other arguments except first are passing correctly).

Now I am getting the "CSPROPI target is not a number" error and I can't find a workaround. As far as I have understood through the code, the problem seems to be related to replacement of CSPROP with CSPROPI instruction at some moment of code generation. The latter instruction expects a number on stack?, but gets a string.

The problem occurs at line 6962 of tsc.js (line accessing ts.objectAllocator.getSymbolConstructor()). Trying to split this line into multiple expressions (keeping intermediate values in variables) resulted in "CSREGI target is not a number" error.

Can you please help to solve this problems? The tsc.js code seems to be a great stress-test to  duktape.

**Comment by zapolnov** [comment] 2015-02-06 18:56
Here is also a test project for a problem with createSourceFile:
https://www.dropbox.com/s/966po0fj6dhtn39/test2.zip?dl=0

If you run it, you will see it printing:

createSourceFile passing: ior.ts
createSourceFile inside: 268

And if you take a look into the code (you may search by "createSourceFile"), you will see that it should not change to 268.

**Comment by svaarala** [comment] 2015-02-06 20:03
Thanks, I'll look into these. I tried the test with assertions enabled and got the same result (CSPROPI target is not a number).

The most likely cause is that a VM registry index has overflowed (there are some hard limits for these) without the existing compiler checks noticing it. If this is the case, it would also unfortunately mean that fixing the limit check will cause a compile error due to the function being too large to compile (e.g. it has too many constants or such).

But, we'll see what turns up. Thanks for reporting the issue!

**Comment by svaarala** [comment] 2015-02-06 20:45
The root cause seems to be a case where the compiler determines in pass 1 compilation that shuffle registers are not needed, but in pass 2 they turn out to be necessary after all. When this happens the shuffle registers are all zero, which causes CSPROPI to use an incorrect register for shuffling.

This also explains why Duktape would corrupt the first argument in such cases, as the first argument maps to register zero.

I can remove the issue by forcing shuffle registers to be allocated for all functions - this is not a proper fix because it impacts also functions that don't need them (which is a majority of functions). I'll need to think about a proper way to fix this, perhaps retrying pass 2 in this special case.

Anyway, I pushed a temporary fix (not merged to master) if you want to test it.

**Comment by svaarala** [comment] 2015-02-06 20:46
Here's the branch:

https://github.com/svaarala/duktape/tree/fix-cspropi-not-number-gh115

**Comment by svaarala** [comment] 2015-02-06 21:22
Managed to replicate the argument clobbering in the above test case; couldn't replicate the CSPROPI issue but a related MPUTOBJ shuffle issue is triggered instead, from the same root cause.

The hack fix in the branch makes the test case pass so I think the root cause identified above is correct.

**Comment by zapolnov** [comment] 2015-02-07 11:04
Thank you very much! The "hack fix" seems to solve the problem. I will use it for now for my experiments with TypeScript. I hope you will be able to find a correct solution to merge into the master branch.

**Comment by svaarala** [comment] 2015-02-07 12:32
Good to hear! This was a pretty interesting bug because it only happens with code that is not too small nor too large (w.r.t. variable/temporary count) so it's not triggered by e.g. test262 or emscripten tests - so thanks for reporting it :)

The easiest "proper fix" is probably just to do a pass 3 in this special case.

**Comment by svaarala** [comment] 2015-02-13 21:30
The proper fix is now in master - the compiler now runs a third pass for the rare cases where the need for register shuffling is only discovered in pass 1.

@zapolnov Closing this now - let me know if the fix doesn't work for you.

**Closed by svaarala** 2015-02-13 21:30 UTC
Labels: bug
