### ISSUE TITLE
Finalizer not called

### ISSUE THREAD

**Issue by malapippo** [svaarala/duktape#1550] opened 2017-06-08 14:07 UTC
I noticed a very strange behavior that I suspect it is a bug (currently I'm using duktape version 2.1.0).
I am compiling the program with Visual Studio 10 on Windows 7.

I have a simple test program that calls a function defined in a javascript script. This function has one array argument with a finalizer native function.
 - if the called javascript function does nothing, then the finalizer is called at the end of the function call.
```javascript
function func(array) {
}
```
 - if the called javascript function call the forEach method of the array passed as argument (it happens also with every, some, etc), the finalizer is called only when the heap is destroyed an not when the function call ends.
```javascript
function func(array) {
    array.forEach(function(){});
}
```

If the function is called more times, every time with a new array instance, than this leads to a memory leak.

Below, the complete test code (complete sources here [test.zip](https://github.com/svaarala/duktape/files/1061240/test.zip))
```c++
#include <stdio.h>
#include "duktape.h"

duk_bool_t duk_timeout_callback(void *udata) 
{
	return 0;
}

duk_ret_t finalizer(duk_context *ctx)
{
	printf("finalizer\n");
	return 0;
}

int main(int argc, char *argv[]) 
{
	const char * script = 
		"function func(array) {\n"
		"	array.forEach(function(){});"
		"}\n";

	duk_context *ctx = duk_create_heap_default();
	if (duk_peval_string(ctx, script) != 0)
	{
		printf("Script error: %s\n", duk_safe_to_string(ctx, -1));
	}
	duk_pop(ctx);

	// get global function func
	if (!duk_get_global_string(ctx, "func"))
	{
		printf("Script error: function func is missing\n");
	}

	// push array
	duk_push_array(ctx);
	for (int n = 0; n < 10; n++)
	{
		duk_push_int(ctx, n);
		duk_put_prop_index(ctx, -2, n);
	}

	// set array finalizer
	duk_push_c_function(ctx, finalizer, 1);
	duk_set_finalizer(ctx, -2);

	// call func with one argument
	if (duk_pcall(ctx, 1) != 0)
	{
		printf("Init error: %s\n", duk_safe_to_string(ctx, -1));
	}
		
	system("pause");

	duk_destroy_heap(ctx);

	system("pause");
	return 0;
}
```

**Comment by svaarala** [comment] 2017-06-08 14:19
Could you try calling `Duktape.gc()` twice after the function call (before heap destruction) to see if it's a case of the array getting involved in a reference loop and thus finalized by mark-and-sweep?

**Comment by fatcerberus** [comment] 2017-06-08 14:28
I suspect it that maybe the inner function (the one passed to forEach) is closing over the array and therefore holding onto it longer than usual.  Even though it doesn't reference the array directly, the closure may still be created.  @svaarala, any input?

**Comment by svaarala** [comment] 2017-06-08 14:35
Not yet, I'd first like to see if mark-and-sweep collects it or not. If yes, there's a circular reference somewhere most likely; or there's a refcount discrepancy but that would be now caught by asserts. So the result of that test will provide an idea what to check next.

**Comment by malapippo** [comment] 2017-06-08 14:49
I tried to do as you said. Calling `duk_gc(ctx, 0)` after the function call (even just one time) and before heap destruction, the array's finalizer is called.

**Comment by svaarala** [comment] 2017-06-08 14:56
Okay, so there's no memory leak as such - but for some reason the finalizer gets called via mark-and-sweep rather than refcounting. There are two main reasons for that:
- The .forEach() call somehow involves the array in a collectable reference loop.
- There's a refcount discrepancy.

One further test might be to use a native function as the .forEach() argument, e.g. `array.forEach(Math.cos)` just to see if the function type makes a difference (there are differences between scope handling for example).

Another useful test would be to enable `DUK_USE_ASSERTIONS` and `DUK_USE_GC_TORTURE` to see if refcount assertions are triggered.

**Comment by svaarala** [comment] 2017-06-08 14:59
I think the cause in this case might be that the `function () {}` in the .forEach() will capture the outer scope containing `array`. Because each function is a reference loop (via its `.prototype` property) this places `array` in the same reference loop and requires mark-and-sweep to collect.

If this is the case, you should be able to avoid the issue with this:

```js
function dummy() {}
function test(array) {
    array.forEach(dummy);
}
```

**Comment by fatcerberus** [comment] 2017-06-08 15:04
Yep, that's what I suspected - the inner function closes over the array creating a reference loop.

**Comment by malapippo** [comment] 2017-06-08 15:06
As you said using array.forEach(Math.cos) the array finalized is called at function call exit.

Also with DUK_USE_GC_TORTURE the array finalized is called at function call exit.
DUK_USE_ASSERTIONS does not trigger any assertion.

**Comment by svaarala** [comment] 2017-06-08 15:11
@malapippo So with these tests I'd say there's no bug as such, but it's a current limitation where an inner Ecmascript captures an outer function's variable values - and because the inner function is in a reference loop it needs mark-and-sweep to be collected. This also means that the captured values will wait for mark-and-sweep collection.

You can work around it now by placing the callback outside the function accepting the `array` argument, or just accepting that some finalizer calls will be mark-and-sweep driven. That happens periodically (and immediately if an allocation fails) without any explicit GC calls.

There are two planned improvements (though I don't know when they'll be implemented) to this:
- Make the function prototype object (`.prototype`) a "spawn on demand" property which avoids the reference loop unless a function is constructed or its `.prototype` is explicitly accessed (rare for non-constructors).
- Clean up scope references on function exit to allow more values to be finalized/freed through reference counting, even if an inner function itself needs mark-and-sweep to be collected.

**Comment by svaarala** [comment] 2017-06-08 15:14
In general there are no strict guarantees for immediate finalizer execution - even for objects not in reference loops. Typically they get finalized quickly by reference counting but there are some corner cases where even refcount finalization gets delayed. For example, objects that become unreachable during debugger paused state get mark-and-sweep collected even if they would normally be finalized immediately.

But obviously it's still preferable for finalization and collection to be as immediate as possible, so this is something that can and should be improved on.

**Comment by malapippo** [comment] 2017-06-08 15:25
Ok, I've understood. 
Because I need to call multiple times the function without destroying the heap, a safe solution could be to explicitly call mark-and-sweep between one call and the other.

Thank you very much for your quick support!

**Comment by svaarala** [comment] 2017-06-08 15:27
@malapippo Even if you don't call GC explicitly, it will get called from time to time -- and every time an allocation fails, i.e. on low memory conditions.

**Closed** 2017-06-13 14:23 UTC
Labels: question
