### ISSUE TITLE
Use of Proxy in global table

### ISSUE THREAD

**Issue by crazyjul** [svaarala/duktape#221] opened 2015-07-16 07:29 UTC
When assigning a Proxy using duk_set_global_table(), the behavior is inconsistent. I use this to intercept global var access and serve a binding

In my tests, duk_eval(ctx, "print('x')" ) does not lookup through the proxy, while duk_eval(ctx, "this.print('x')" ) looks the proxy up using the 'get' function

I suggest either to modify the behavior or update the documentation with this Proxy limitation

Thanks

**Comment by svaarala** [comment] 2015-07-16 07:32
Function calls are caught by the `apply` trap which Duktape doesn't yet implement.

**Comment by svaarala** [comment] 2015-07-16 07:37
As for the difference in `get` trap behavior, the `print(x)` case is handled by variable lookup code which doesn't currently invoke the proxy behavior. This should be fixed as a proxy may also be used as a "with" binding and the same limitation will probably apply for that case too.

**Comment by crazyjul** [comment] 2015-07-16 07:49
Cool, if you consider it a bug, I can have a look to fix it.

For the apply, I don't use it for now, simple get followed by a call on the result is sufficent for me

Thanks

**Comment by svaarala** [comment] 2015-07-16 16:41
The fix would be to either support Proxy objects for "object bindings" explicitly, or change the variable lookup code to use ordinary property operations (getprop etc instead of looking up duk_tval pointers and handling getter/setter properties specially). All in all the property lookup slow path code would benefit from a rewrite, it hasn't been changed in a long time.

**Comment by svaarala** [comment] 2015-08-11 20:31
Draft branch with fix here: https://github.com/svaarala/duktape/compare/object-binding-proxy-support

Because all global object lookups go through this slow path (e.g. any code that does `print("foo")`), it might be worth having a separate code path for non-Proxy objects and avoid the slightly slower `duk_hobject_hasprop()` call. I'll have to measure the impact.

**Comment by svaarala** [comment] 2015-08-14 12:34
Merged to master.

**Closed by svaarala** 2015-08-14 12:34 UTC
Labels: bug

**Comment by faywong** [comment] 2016-03-16 04:46
@svaarala
>>Function calls are caught by the apply trap which Duktape doesn't yet implement.
Is there a plan to implement 'apply' trap? I need to use Proxy feature to implement 'dynamic binding' so as not to change the c code frequently.

**Comment by svaarala** [comment] 2016-03-16 09:15
@faywong Do you need to virtualize the call into the Proxy itself (`myproxy(1,2,3)`) or calls into Proxy properties (`myproxy.func(1,2,3)`)? The latter is possible even now, because the call invokes the 'get' trap for 'func' which allows you to virtualize that call.

**Comment by faywong** [comment] 2016-03-17 07:08
I mean the latter one. However i can't get some clue about "the call invokes the 'get' trap" in the [virutal properties guide](http://wiki.duktape.org/HowtoVirtualProperties.html). Maybe i use the v1.3 and you are discussing a newer version.

**Comment by svaarala** [comment] 2016-03-17 09:34
I'll try to improve the documentation, but the main reason is that a Proxy catches operations that happen directly on the Proxy object, for example `myproxy.foo` (get trap) or `myproxy()` (apply trap).

When you call `myproxy.func()` there are actually two separate operations:

- Property lookup, which happens on the Proxy and thus invokes the "get" trap.
- Once the property lookup completes, a function call on the property value. This doesn't involve the Proxy anymore (other than the Proxy becoming the "this" binding for the call).

As far as the Proxy is concerned `myproxy.func(1, 2, 3)` is equivalent to:

    var v = myproxy.func;  // lookup function
    v.call(myproxy, 1, 2, 3);  // call the function, using 'myproxy' for the 'this' binding

**Comment by faywong** [comment] 2016-03-17 14:09
@svaarala  I also noticed a crash when evaluate(v1.3.2):

Quote from [HowtoVirtualProperties](http://wiki.duktape.org/HowtoVirtualProperties.html)

```javascript
// Underlying plain object.
var target = { foo: 'bar' };

// Handler table, provides traps for interaction (can be modified on-the-fly).
var handler = {
    has: function (targ, key) {
        print('has called for key=' + key);
        return key in targ;  // return unmodified existence status
    }

    get: function (targ, key, recv) {
        print('get called for key=' + key);
        return targ[key];  // return unmodified value
    },

    set: function (targ, key, val, recv) {
        print('set called for key=' + key + ', val=' + val);
        targ[key] = val;  // must perform write to target manually if 'set' defined
        return true;      // true: indicate that property write was allowed
    },

    deleteProperty: function (targ, key) {
        print('deleteProperty called for key=' + key);
        delete targ[key];  // must perform delete to target manually if 'deleteProperty' defined
        return true;       // true: indicate that property delete was allowed
    }
};

// Create proxy object.
var proxy = new Proxy(target, handler);

// Proxy object is then accessed normally.
print('foo' in proxy);
proxy.foo = 321;
print(proxy.foo);
delete proxy.foo;
```

the stack trace is:

![image](https://cloud.githubusercontent.com/assets/1934627/13848459/e293bf28-ec8c-11e5-8b9f-645f623b534c.png)

**Comment by svaarala** [comment] 2016-03-17 15:45
That crash is actually caused by an uncaught exception which triggers the fatal error handler. By adding a try-catch (or running the example with the "duk" command line tool):

```
$ ./duk /tmp/foo.js
SyntaxError: invalid object literal (line 11)
	/tmp/foo.js:11
	duk_js_compiler.c:3186
```

There's a missing comma in the example on line 11 (for the "has" property). I'll fix the example in the Wiki: https://github.com/svaarala/duktape-wiki/pull/103.

**Comment by svaarala** [comment] 2016-03-17 15:53
Ok, fixed in the Wiki example. Sorry about that :)

**Comment by faywong** [comment] 2016-09-07 04:01
Quote from @svaarala

**Comment by faywong** [comment] 2016-09-07 04:06
Quoto from @svaarala 
>When you call myproxy.func() there are actually two separate operations:
>
>Property lookup, which happens on the Proxy and thus invokes the "get" trap.
>Once the property lookup completes, a function call on the property value. This doesn't involve >the Proxy anymore (other than the Proxy becoming the "this" binding for the call).

Is there some utility to override the "get" trap in c code? I have read through the api docs once again and got no clue.

Also i am curious about how can i print a human-friendly log(such as the related javascript code snippets and point out the start position of error with a up arrow) to help locate the issue easy.

**Comment by svaarala** [comment] 2016-09-07 04:24
> Is there some utility to override the "get" trap in c code? I have read through the api docs once again and got no clue.

Hmm, I'm not sure what you mean in practice - but if you simply want to use a native "get" trap, you can simply set the `.get` property of the Proxy handler table with a Duktape/C function from native code.

For example, if you build your Proxy mainly from C code, you could do something like:

```c
/* Use an intermediate helper function for Proxy initialization; leave function on stack. */
duk_eval_string(ctx, "(function (target, handlers) { return new Proxy(target, handlers); })");

/* Push target object. */
duk_dup(ctx, target_idx);  /* or create object from scratch, etc */

/* Create handlers table; just .get here */
duk_push_object(ctx);
duk_push_c_function(ctx, my_get_trap, 3);
duk_put_prop_string(ctx, -2, "get");

/* At this point value stack contains:
 * [ helperFunc target handlers ]
 */

duk_call(ctx, 2);

/* And here the three values are replaced with just:
 * [ proxyObject ]
 */
```

There are many other approaches too; you can create the Proxy entirely from Ecmascript code but retain a reference to the handlers table somehow (via a global for example). You can then edit the handlers table from C code, e.g. add or modify trap properties (`.get` etc).

**Comment by svaarala** [comment] 2016-09-07 04:26
> Also i am curious about how can i print a human-friendly log(such as the related javascript code snippets and point out the start position of error with a up arrow) to help locate the issue easy. 

If you eval code yourself and encounter a SyntaxError (or any other error), the error object contains a `.lineNumber` property. You could then combine the source and the lineNumber to highlight a source line containing the potential error.

Duktape lexer doesn't currently keep track of column-level information so you wouldn't be able to point an arrow to a specific character on a line right now.

**Comment by svaarala** [comment] 2016-09-07 18:07
The alternative for that eval-based Proxy creation is something like:

```c
duk_get_global_string(ctx, "Proxy");
duk_dup(ctx, target_idx);  /* push/init target object */
duk_push_object(ctx);  /* push and init handlers table */
/* ... handlers init ... */
duk_new(ctx, 2);  /* [ Proxy target handlers ] -> [ proxyInstance] */
```

An eval-based helper is sometimes more convenient (not necessarily here) because it's easy, for example, to build the handlers table in Ecmascript code, perhaps log something, catch errors, etc.

**Comment by faywong** [comment] 2016-09-08 03:32
>Hmm, I'm not sure what you mean in practice - but if you simply want to use a native "get" trap, you can simply ...

Thanks for your detailed explanation which is what i want. And before you told me the trick to implement a native "get" trap at above i should have thought there's a straight-forward api in c to support it.

Anyway, many many thanks to you. 
Maybe someday i could help translate the docs、tricks & best practice into Chinese when i am free.

**Comment by svaarala** [comment] 2016-09-08 10:50
I understand, at present not all Ecmascript bindings have a corresponding C binding, as doing so would increase the API call count a great deal. Then again, for every individual feature (like Proxy here) it would seem to make sense to add a C binding, so the situation is a bit labile. Maybe adding a Proxy C binding would make sense, if it made initializing Proxy objects significantly more convenient.

> Maybe someday i could help translating the docs, tricks & best practice into Chinese when i am free.

That would be awesome. I'll need to figure out how to handle localization for the website and the Wiki before that :)
