### ISSUE TITLE
SyntaxError: invalid regexp character

### ISSUE THREAD

**Issue by faywong** [svaarala/duktape#1465] opened 2017-04-06 09:42 UTC
When i load protobuf.js & evaluate it in duktape, there is an error:

```shell
SyntaxError: invalid regexp character (line 218)
```
[line 218 of protobuf.js](https://github.com/dcodeIO/protobuf.js/blob/master/dist/protobuf.js#L218)

```javascript
var blockOpenRe  = /[{[]$/,
    blockCloseRe = /^[}\]]/,
    casingRe     = /:$/,
    branchRe     = /^\s*(?:if|}?else if|while|for)\b|\b(?:else)\s*$/, // line 218
    breakRe      = /\b(?:break|continue)(?: \w+)?;?$|^\s*return\b/;
```

Which regex character is not suported?

**Comment by svaarala** [comment] 2017-04-06 10:39
I think it's the unescaped curly brace `}`. These are accepted by Duktape since the 1.5.0 release:

> * Allow ES2015 unescaped curly braces ('{' and '}') in regular expressions (non-standard before ES2015 Annex B) when no valid quantifier can be parsed; this improves compatibility with existing Javascript code which often assumes support for literal curly braces (GH-142, GH-513, GH-547, GH-565)

**Comment by svaarala** [comment] 2017-04-16 20:03
I'll close this now as the issue is already fixed in 1.5.0.

**Closed by svaarala** 2017-04-16 20:03 UTC
Labels: question

**Comment by faywong** [comment] 2017-05-07 14:16
@svaarala Got it. Thanks for your clarifying.

**Comment by bulbaasd** [comment] 2022-08-18 13:38
Hi @faywong were you able to use protobufjs with duktape? I understand that promise and xhr polyfills are required.

**Comment by faywong** [comment] 2022-12-08 01:59
> Hi @faywong were you able to use protobufjs with duktape? I understand that promise and xhr polyfills are required.

Yes, i have implemented them separately.
