### ISSUE TITLE
Option for Duktape to use UTF-16 internally

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#1700] opened 2017-08-27 15:20 UTC
Many major JavaScript engines use UTF-16, both internally and in their API.  This makes it difficult to write a generic abstraction that also works with Duktape, as these engines expose strings through their API as `wchar_t*` instead of `char*`.  Consider adding an option to use UTF-16 for the internal representation instead of UTF-8.

**Comment by svaarala** [comment] 2017-08-27 16:57
That's been suggested from time to time, but I think it would be too much work for the benefit. It would affect a lot of the internals, prevent using libc functions like s(n)printf() as is, and the C API would no longer be able to work with ordinary strings.

So, unless there's a good argument why this can be easily done, I'm quite against this change.

**Comment by svaarala** [comment] 2017-08-27 17:10
If the main motivation behind UTF-16 support is the C API -- and not that UTF-16 would be better internally -- one alternative change would be to add API calls to get strings as UTF-16 but still represent them internally in extended UTF-8. This could be made to work as follows:
- When a string is interned, just create the internal representation.
- When an UTF-16 representation is requested, lazily create a UTF-16 variant of the string, with the allocation referenced by the original interned duk_hstring so that it gets freed with the string.

This would lead to higher memory usage than just UTF-16 or just extended UTF-8, but API-wise it would allow one to deal with both representations, and still be able to have stable string data pointers whose lifetime was tied to the underlying duk_hstring.

I wouldn't want this to be enabled by default because it costs one more pointer for each duk_hstring (unless a separate data structure tracked the converted string copies).

Anyway, this would be a fraction of the work of actually converting the internal representation, and at least within the realm of possibility :)

**Comment by fatcerberus** [comment] 2017-08-27 17:37
> If the main motivation behind UTF-16 support is the C API -- and not that UTF-16 would be better internally -- one alternative change would be to add API calls to get strings as UTF-16 but still represent them internally in extended UTF-8

Yes, this would serve the purpose. :)

I wouldn't mind transcoding happening as long as it's done lazily and Duktape still freed the string for me.

**Comment by svaarala** [comment] 2017-08-27 17:47
That's good to hear :) I think somerthing like this would be relatively easy to implement. It should work pretty straightforwardly because strings are immutable and the lifecycle of strings is easy to control (= there's just one function actually freeing them).

**Comment by fatcerberus** [comment] 2017-08-27 17:51
As far as API naming goes it could probably be something like `duk_xxx_wstring()`.  It should be possible to push wide strings as well.

This would be a net gain for Win32 developers as well, since the Windows API uses wide strings.

**Comment by svaarala** [comment] 2017-08-27 17:54
One thing I'm a bit concerned about is that if the C API is changed to use actual UTF-8 (WTF-8 to support a larget set of strings) it will be aligned with the full UTF-8 codepoint space. UTF-16 would be, again, dealing with surrogate pairs and thus a little bit a step backwards IMO.

Also, if Ecmascript standard eventually adopts a way of supporting non-BMP characters properly (which I really, really hope will happen because it'd be much simpler for users) the UTF-16 representation would again be a bit of a weird outlier.

But, as long as it's translation based, it will only affect some code at the edges.

**Comment by svaarala** [comment] 2017-08-27 20:21
It seems `wchar_t` has relatively few guarantees re: portability; it may even be 8 bits. It may also be 32 bits, so that full Unicode could be used (instead of UTF-16 and surrogate pairs).

From Wikipedia:
> Both C and C++ introduced fixed-size character types char16_t and char32_t in the 2011 revisions of their respective standards to provide unambiguous representation of 16-bit and 32-bit Unicode transformation formats, leaving wchar_t implementation-defined. The ISO/IEC 10646:2003 Unicode standard 4.0 says that: "The width of wchar_t is compiler-specific and can be as small as 8 bits. Consequently, programs that need to be portable across any C or C++ compiler should not use wchar_t for storing Unicode text. The wchar_t type is intended for storing compiler-defined wide characters, which may be Unicode characters in some compilers." 

I guess the practical issue is that if any platform APIs accept `wchar_t`, then one would just want Duktape to provide strings encoded as `wchar_t` whatever that may be. It's then a separate question whether e.g. surrogates should be combined (if wchar_t is 32 bits) or not.

**Comment by fatcerberus** [comment] 2017-08-27 22:09
8-bit wchar_t would be easy at least: You don't even need to transcode.  16-bit would get UTF-16 encoded (with surrogate pairs) and 32-bit maps 1:1 with scalar values.

**Comment by svaarala** [comment] 2017-08-27 22:19
I think you're glossing over a lot of potential details :-)

Does 8-bit `wchar_t` mean that the platform is expecting UTF-8? That would seem contrary to the idea of wide characters. If it means a certain encoding, then that implies transcoding with some replacement strategy.

Similarly, does a 16-bit `wchar_t` mean that the platform deals with surrogates correctly? What about unpaired surrogates; do they need replacement or not (e.g. Windows apparently accepts unpaired surrogates in filenames)? Does a 32-bit `wchar_t` mean the full Unicode range is supported? Does it mean unpaired surrogates are accepted?

**Comment by fatcerberus** [comment] 2017-08-27 22:45
Windows filenames are actually not even UTF-16 but just a raw array of widechars without any kind of interpretation.  They are UTF-16 "in name only".

That said, most of the Win32 API does treat widechar strings as UTF-16 as far as I'm aware.  For historical reasons, "Unicode" = UTF16 as far as windows is concerned.

**Comment by svaarala** [comment] 2017-08-27 22:59
Right, so on Windows the expected behavior would be for non-BMP to be encoded as surrogate pairs, and unpaired surrogates (CESU-8 internally) to be accepted as is.

But does this hold for other platforms where `wchar_t` is 16 bits?

**Comment by fatcerberus** [comment] 2017-08-27 22:59
> I think you're glossing over a lot of potential details :-)

Probably - that was mostly just thinking aloud, I didn't mean it to be a concrete suggestion for how to move forward. :)

**Comment by denisdemaisbr** [comment] 2017-08-28 21:37
Q:
1. utf-16 is endianess /?
2. this will be mandatory or optional ?

some background: http://unicode.org/faq/utf_bom.html

**Comment by svaarala** [comment] 2017-08-28 21:52
Assuming the feature would be providing `wchar_t *` strings, the wide characters are in memory in the native layout so that e.g. platform API calls could use them as is.

If implemented, this would be optional.

**Comment by fatcerberus** [comment] 2017-09-01 04:21
@svaarala In my case, it turns out that Duktape exposing WTF-8 would be enough for interoperability, as Chakra has functions in its API for working with UTF-8 strings.  I was mistaken in my initial impression that UTF-16 was the only available interface.

By the way, I found out the hard way (after spending half a day hunting a segfault :) that `sizeof(wchar_t)` is 4 on both Linux and macOS.  The `wchar_t`-based APIs in Chakra are in fact deprecated on non-Windows platforms for exactly that reason (the string is encoded as UTF-16 regardless, making it invalid when wchar_t is not 16-bit).

**Comment by denisdemaisbr** [comment] 2017-09-01 04:49
utf-8 uses 1,2 or 4 bytes (uint8_t) to indicate a character * and can encode all utf charset

to avoid this rework can be a function and/or custom duk buffer ?

* http://kunststube.net/encoding/
* https://stackoverflow.com/questions/2241348/what-is-unicode-utf-8-utf-16

**Comment by svaarala** [comment] 2017-09-01 09:13
@denisdemaisbr Yes, one solution is to encode/code strings as needed. @fatcerberus's request was for Duktape to do that automatically (either using an internal representation in UTF-16, or providing an automatic conversion on demand).

**Comment by svaarala** [comment] 2022-04-08 18:28
Current approach is to use WTF-8 as internal representation which can be 1:1 mapped to UTF-16 as needed. Closing this one.

**Closed by svaarala** 2022-04-08 18:28 UTC
