### ISSUE TITLE
Regex Error with Typescript 2.4.2

### ISSUE THREAD

**Issue by rodrigolive** [svaarala/duktape#1687] opened 2017-08-17 08:24 UTC
I'm getting this error:

    SyntaxError: invalid regexp escape

Originating in this Typescript 2.4.2 regex:

     var tripleSlashDirectiveFragmentRegex = /^(\/\/\/\s*<reference\s+(path|types)\s*=\s*(?:'|"))([^\3"]*)$/;

The offending regex fragment is the `[^\3"]` part, apparently Duktape does not support backtracking inside a negated character class...? Here's a short version of it:

   /(a)b[^\1]/.test('aba');

Should work and yield false but errors out instead. Any workarounds welcome.

**Comment by svaarala** [comment] 2017-08-17 08:31
That's already fixed in master, see #1276.

Note that `\3` in a chararacter class is not a backref but an octal literal, matching U+0003, which is probably not intended.

**Closed by svaarala** 2017-08-17 08:31 UTC

**Comment by svaarala** [comment] 2017-08-17 08:33
The fix was actually merged for 2.1.0 so it's also released.

**Comment by rodrigolive** [comment] 2017-08-17 13:54
Great, thanks, but the fix merged makes the `\3` behave as octal or as a backtracked element in the character class?

**Comment by svaarala** [comment] 2017-08-17 18:27
As octal - the same way it behaves in Node.js, see #1276. The unit tests were confirmed against Node.js.

**Comment by svaarala** [comment] 2017-08-17 18:34
Oops, the correct issue was actually #1275 (also edited comments above). The pull implementing the fix was #1483.
