### ISSUE TITLE
Uncaught error during debugger Eval generates fatal Throw notify

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#558] opened 2016-01-26 06:52 UTC
...it's actually even worse than that: Duktape apparently halts execution in the Eval code since the filename in the Status notify is "input".  This confuses my debug client to no end (it doesn't expect execution to pause there ;) ), somehow ultimately leading to Duktape sending a Detaching notify with the error flag set.  I haven't pinned down the precise chain of events that causes the errant detach yet, my message handling is currently a bit rickety. :)

**Comment by svaarala** [comment] 2016-01-26 09:15
Is this a duplicate of #379?

**Comment by svaarala** [comment] 2016-01-26 09:22
Just to clarify what do you mean by "uncaught error"? Do you mean that the Eval code throws an error which is not caught within the eval code itself - in other words, it is caught only by the protected call in the debugger code which handles an Eval command?

If so, here's what happens for me with Throw notify enabled (but without the option to halt on uncaught error). This is a JSON debug proxy session running `test-dev-mandel2-func.js`.

```
; Connect
{"notify":"_Connected","args":["1 10499 v1.4.0-59-g9915b45 duk command built from Duktape repo"]}
{"notify":"Status","command":1,"args":[1,"test-dev-mandel2-func.js","global",58,0]}

; Add breakpoint
{"request":"AddBreak","args":["test-dev-mandel2-func.js",86]}
{"reply":true,"args":[0]}

; Resume and pause at breakpoint
{"request":"Resume"}
{"reply":true,"args":[]}
{"notify":"Status","command":1,"args":[0,"test-dev-mandel2-func.js","global",58,0]}
{"notify":"Status","command":1,"args":[1,"test-dev-mandel2-func.js","mandel",86,45]}

; Eval with eval code throwing an uncaught error (= Eval handler catches it)
; Result: Throw notify, eval reply
{"request":"Eval","args":["throw new Error('foo')"]}
{"notify":"Throw","command":5,"args":[0,"Error: foo","input",1]}
{"reply":true,"args":[1,"Error: foo"]}

; Resume, hit breakpoint again
{"request":"Resume"}
{"reply":true,"args":[]}
{"notify":"Status","command":1,"args":[0,"test-dev-mandel2-func.js","mandel",86,45]}
{"notify":"Status","command":1,"args":[1,"test-dev-mandel2-func.js","mandel",86,45]}

; Delete breakpoint and resume normally
{"request":"DelBreak","args":[0]}
{"reply":true,"args":[]}
{"request":"Resume"}
{"reply":true,"args":[]}
{"notify":"Status","command":1,"args":[0,"test-dev-mandel2-func.js","mandel",86,45]}
{"notify":"Status","command":1,"args":[0,"test-dev-mandel2-func.js","mandel",88,54]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["........................................#.......................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["....................................####........................................\n"]}
{"notify":"Print","command":2,"args":["....................................####........................................\n"]}
{"notify":"Print","command":2,"args":["..............................#..##########.....................................\n"]}
{"notify":"Print","command":2,"args":["..............................#################.................................\n"]}
{"notify":"Print","command":2,"args":["............................###################.................................\n"]}
{"notify":"Print","command":2,"args":["...........................#####################................................\n"]}
{"notify":"Print","command":2,"args":[".................#######..######################................................\n"]}
{"notify":"Print","command":2,"args":["................#########.######################................................\n"]}
{"notify":"Print","command":2,"args":[".#############################################..................................\n"]}
{"notify":"Print","command":2,"args":["................#########.######################................................\n"]}
{"notify":"Print","command":2,"args":[".................#######..######################................................\n"]}
{"notify":"Print","command":2,"args":["...........................#####################................................\n"]}
{"notify":"Print","command":2,"args":["............................###################.................................\n"]}
{"notify":"Print","command":2,"args":["..............................#################.................................\n"]}
{"notify":"Print","command":2,"args":["..............................#..##########.....................................\n"]}
{"notify":"Print","command":2,"args":["....................................####........................................\n"]}
{"notify":"Print","command":2,"args":["....................................####........................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["........................................#.......................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Detaching","command":6,"args":[0]}
{"notify":"_Disconnecting"}
```

**Comment by fatcerberus** [comment] 2016-01-26 15:15
Not a duplicate I don't think - #379 is about an error thrown _during a halt-on-throw_ becoming a double error due to the handling_error flag still being set.  This is a different thing.

It's "uncaught" as per the Throw notify code (= no Ecmascript catcher), I know the Eval handler catches it. :)

Looking at your test above, it's interesting that the Throw notify you get has fatal = 0.  I'm getting fatal = 1 and an accompanying execution pause.  This leads me to think your breakpoint is inside of a try-catch.

What happens if you enable halt on throw, set a breakpoint, and then perform an Eval which throws while outside of a try-catch?

**Comment by svaarala** [comment] 2016-01-26 15:23
You're right, the Eval is inside the try-catch guard of the mandelbrot try-catch wrapper. I'll retest it later tonight.

**Comment by svaarala** [comment] 2016-01-26 15:24
Anyway, the expected behavior would be that there's a Throw notify with "fatal=1" for the error thrown inside Eval, and then an Eval reply indicating an error? So the sequence I posted above (from JSON proxy) but with fatal=1.

**Comment by fatcerberus** [comment] 2016-01-26 16:18
Just to make it clear: I don't think the bug is with the throw notify code specifically, but rather with the pause-on-throw option.  When fatal=1 Duktape halts execution and enters another debugger loop (`duk_debug_halt_execution()`), which delays delivery of the Eval reply and knocks things out of sync.

The errant detach mentioned above is most likely caused by a bug in my client, so don't pay too much mind to that. :)

**Comment by svaarala** [comment] 2016-01-26 18:22
Ok, should be possible to reproduce. So the desired behavior would be the JSON proxy sequence with fatal=1 without trying to halt again I think.

**Comment by svaarala** [comment] 2016-01-26 18:38
Looking at code this seems a bit odd. The error handling code is not intended to activate at all when debugger command processing is running: https://github.com/svaarala/duktape/blob/master/src/duk_error_misc.c#L88-L90. `!thr->heap->dbg_processing` should be false: https://github.com/svaarala/duktape/blob/master/src/duk_debugger.c#L1849-L1855. This assert should also be raised: https://github.com/svaarala/duktape/blob/master/src/duk_debugger.c#L1814 because we're already in the message processing loop.

**Comment by fatcerberus** [comment] 2016-01-26 19:21
Hm, I'm not sure, I'm definitely getting a Status notify with status=1 immediately after the throw, I've verified that under MSVC's debugger.  I'll turn on assertions and see if anything shows up.

**Comment by fatcerberus** [comment] 2016-01-26 19:52
Here's something interesting:

```
Starting minisphere... OK.
Connecting to 127.0.0.1:1208... OK.
Handshaking... OK.
  Attached to minisphere 2.99.812
  Duktape v1.4.0

scripts/main.js:6 ssj$ go
Resuming execution at scripts/main.js:6... OK.
Spectacles: Bruce's Story miniRT Console
Sphere API v2.0 (minisphere 2.99.812)

Initializing Specs Engine test harness
Loading testcases from 'brucesStory.js'
Added battle test 'rsbBalcony'
Added battle test 'rsbFinal'
Loading testcases from 'lastLucidan.js'
Added battle test 'temple'
Uncaught Error: pig eaten by cow <scripts/main.js:46>

scripts/main.js:46 ssj$ eval pig
Evaluating JS expression... OK.
ReferenceError: identifier 'pig' undefined
```

Above, execution halts on an uncaught error, and the errant Eval works as expected: Eval's reply has flag=1 (error), and the string-coerced error.  However, if instead I cause the error at the outset:

```
Starting minisphere... OK.
Connecting to 127.0.0.1:1208... OK.
Handshaking... OK.
  Attached to minisphere 2.99.812
  Duktape v1.4.0

scripts/main.js:6 ssj$ eval pig
Evaluating JS expression... Uncaught ReferenceError: identifier 'pig' undefined <input:1>
minisphere detached due to an error.
^C
```

So there's definitely a difference in behavior on Duktape's side.  Notice it never prints the "OK.", meaning the Detaching notify and disconnect happen before the reply is received. (the ^C is because the client got confused there and locked up)

**Comment by fatcerberus** [comment] 2016-01-26 20:00
Oh, I forgot to mention: Despite the odd behavior in the second case, no asserts seem to have been triggered.

**Comment by svaarala** [comment] 2016-01-26 20:26
Running with an additional debug print:

```
[D] duk_error_misc.c:91 (duk_err_setup_heap_ljstate): check for throw notify: attached=1, processing=0, type=1
```

So in the longjmp setup code `thr->heap->dbg_processing = 0` while we're executing eval.

**Comment by svaarala** [comment] 2016-01-26 20:28
No asserts are fired, and I don't get any protocol issues when the `mandel()` call is not try-catch protected:

```
sva@keppihevonen:~$ telnet localhost 9093
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
{"notify":"_Connected","args":["1 10499 v1.4.0-61-g7dd8799-dirty duk command built from Duktape repo"]}
{"notify":"Status","command":1,"args":[1,"foo.js","global",58,0]}
{"request":"AddBreak","args":["foo.js",86]}
{"reply":true,"args":[0]}
{"request":"Resume"}
{"reply":true,"args":[]}
{"notify":"Status","command":1,"args":[0,"foo.js","global",58,0]}
{"notify":"Status","command":1,"args":[1,"foo.js","mandel",86,45]}

; Here doing the Eval
{"request":"Eval","args":["throw new Error('aiee')"]}

; Throw notify, this time "fatal" is 1
{"notify":"Throw","command":5,"args":[1,"Error: aiee","input",1]}

; Eval reply
{"reply":true,"args":[1,"Error: aiee"]}

; DelBreak and resume normally
{"request":"DelBreak","args":[0]}
{"reply":true,"args":[]}
{"request":"Resume"}
{"reply":true,"args":[]}
{"notify":"Status","command":1,"args":[0,"foo.js","mandel",86,45]}
{"notify":"Status","command":1,"args":[0,"foo.js","mandel",88,54]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["........................................#.......................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["....................................####........................................\n"]}
{"notify":"Print","command":2,"args":["....................................####........................................\n"]}
{"notify":"Print","command":2,"args":["..............................#..##########.....................................\n"]}
{"notify":"Print","command":2,"args":["..............................#################.................................\n"]}
{"notify":"Print","command":2,"args":["............................###################.................................\n"]}
{"notify":"Status","command":1,"args":[0,"foo.js","mandel",88,54]}
{"notify":"Print","command":2,"args":["...........................#####################................................\n"]}
{"notify":"Print","command":2,"args":[".................#######..######################................................\n"]}
{"notify":"Print","command":2,"args":["................#########.######################................................\n"]}
{"notify":"Print","command":2,"args":[".#############################################..................................\n"]}
{"notify":"Status","command":1,"args":[0,"foo.js","mandel",88,54]}
{"notify":"Print","command":2,"args":["................#########.######################................................\n"]}
{"notify":"Print","command":2,"args":[".................#######..######################................................\n"]}
{"notify":"Print","command":2,"args":["...........................#####################................................\n"]}
{"notify":"Print","command":2,"args":["............................###################.................................\n"]}
{"notify":"Print","command":2,"args":["..............................#################.................................\n"]}
{"notify":"Status","command":1,"args":[0,"foo.js","mandel",88,54]}
{"notify":"Print","command":2,"args":["..............................#..##########.....................................\n"]}
{"notify":"Print","command":2,"args":["....................................####........................................\n"]}
{"notify":"Print","command":2,"args":["....................................####........................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["........................................#.......................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Detaching","command":6,"args":[0]}
{"notify":"_Disconnecting"}
```

**Comment by fatcerberus** [comment] 2016-01-26 20:29
Is this with pause-on-throw enabled?

**Comment by svaarala** [comment] 2016-01-26 20:30
Just to clarify, I don't have "halt on uncaught" defined which probably explains why nothing goes really wrong in my case.

However, given the guard in the longjmp handler, no Throw notify should be sent during Eval. (One can then argue which behavior is desirable.)

**Comment by fatcerberus** [comment] 2016-01-26 20:33
Yeah, the bug is specifically related to halt on uncaught, the throw notify itself is fine (I thought I clarified this above).

**Comment by svaarala** [comment] 2016-01-26 20:36
The intent of the current code is that a Throw notify is *not* sent during a debugger Eval.

I think I found the bug, when the bytecode executor enters debugger message processing loop the code path doesn't set `thr->heap->dbg_processing = 1` which then allows the error handling code to process throw/halt.

**Comment by fatcerberus** [comment] 2016-01-26 20:38
Avoiding the Throw notify will also fix the errant pause, correct?

**Comment by svaarala** [comment] 2016-01-26 20:42
Yes, this is what happens with `dbg_processing` set as expected and with "pause on uncaught" enabled:

```
$ telnet localhost 9093
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
{"notify":"_Connected","args":["1 10499 v1.4.0-61-g7dd8799-dirty duk command built from Duktape repo"]}
{"notify":"Status","command":1,"args":[1,"foo.js","global",58,0]}
{"request":"AddBreak","args":["foo.js",86]}
{"reply":true,"args":[0]}
{"request":"Resume"}
{"reply":true,"args":[]}
{"notify":"Status","command":1,"args":[0,"foo.js","global",58,0]}
{"notify":"Status","command":1,"args":[1,"foo.js","mandel",86,45]}

; Here's the Eval and its reply: no Throw notify
{"request":"Eval","args":["throw new Error('aiee')"]}
{"reply":true,"args":[1,"Error: aiee"]}

; DelBreak and Resume normally
{"request":"DelBreak","args":[0]}
{"reply":true,"args":[]}
{"request":"Resume"}
{"reply":true,"args":[]}
{"notify":"Status","command":1,"args":[0,"foo.js","mandel",86,45]}
{"notify":"Status","command":1,"args":[0,"foo.js","mandel",88,54]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["........................................#.......................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["....................................####........................................\n"]}
{"notify":"Print","command":2,"args":["....................................####........................................\n"]}
{"notify":"Print","command":2,"args":["..............................#..##########.....................................\n"]}
{"notify":"Print","command":2,"args":["..............................#################.................................\n"]}
{"notify":"Print","command":2,"args":["............................###################.................................\n"]}
{"notify":"Print","command":2,"args":["...........................#####################................................\n"]}
{"notify":"Status","command":1,"args":[0,"foo.js","mandel",88,54]}
{"notify":"Print","command":2,"args":[".................#######..######################................................\n"]}
{"notify":"Print","command":2,"args":["................#########.######################................................\n"]}
{"notify":"Print","command":2,"args":[".#############################################..................................\n"]}
{"notify":"Print","command":2,"args":["................#########.######################................................\n"]}
{"notify":"Status","command":1,"args":[0,"foo.js","mandel",88,54]}
{"notify":"Print","command":2,"args":[".................#######..######################................................\n"]}
{"notify":"Print","command":2,"args":["...........................#####################................................\n"]}
{"notify":"Print","command":2,"args":["............................###################.................................\n"]}
{"notify":"Print","command":2,"args":["..............................#################.................................\n"]}
{"notify":"Print","command":2,"args":["..............................#..##########.....................................\n"]}
{"notify":"Print","command":2,"args":["....................................####........................................\n"]}
{"notify":"Print","command":2,"args":["....................................####........................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Status","command":1,"args":[0,"foo.js","mandel",88,54]}
{"notify":"Print","command":2,"args":["........................................#.......................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Print","command":2,"args":["................................................................................\n"]}
{"notify":"Detaching","command":6,"args":[0]}
{"notify":"_Disconnecting"}
```

No issues with the debugger session but there's no Throw notify for the Eval-triggered error either. I don't think that's necessarily a bad feature though because doing recursive debugger messaging is a little bit risky. But in this particular case I think it'd be safe to send the Throw notify but not to try to halt again.

**Comment by svaarala** [comment] 2016-01-26 20:50
Pull #562 fixes the issue at least for me. Overall I'm not very happy with the debugger state handling: for example, there are multiple paths into the debugger message loop so it's easy to some flag handling to differ between the alternate paths.

**Comment by fatcerberus** [comment] 2016-01-26 20:51
I think the Throw notify is probably redundant, the REP for the Eval already includes a flag indicating whether the result is an error or not, so you don't get any additional information out of it.

**Comment by svaarala** [comment] 2016-01-26 20:52
Maybe the Eval reply could also indicate if the error would be caught (in the sense of the "fatal" flag in the Throw notify) so it'd have that missing piece of information?

**Comment by fatcerberus** [comment] 2016-01-26 20:55
Hm, if the error would be caught it will have to be inside the Eval code itself, since otherwise it won't get past the protective sandbox handling the request anyway.  But I can see how Throw notifys during debugger eval could be useful, if you're calling into "black box" functions on the target.

**Comment by svaarala** [comment] 2016-01-26 20:57
You're right - it doesn't really provide useful information because while there's no Ecmascript try-catch, the debugger code protected call will catch the error anyway. Never mind :)

**Comment by fatcerberus** [comment] 2016-01-26 20:59
The only useful info provided by the Throw notify that isn't provided by Eval is the file/line where it was thrown from.

**Comment by fatcerberus** [comment] 2016-02-09 03:02
Okay, just following up to mention that, having done more work with the debugger, the Throw notifys from Eval are proving to be a major nuisance in practice.  So I would be fine with a solution that just avoids generating them during processing of Eval.

**Closed** 2016-02-09 12:00 UTC
Labels: bug, debugger

**Comment by svaarala** [comment] 2016-02-10 09:20
Agree, and with #562 in master there shouldn't be any more Throw notifys (or other debugger messaging) during a debug client initiated Eval.
