### ISSUE TITLE
Alloc Error Loop Handling

### ISSUE THREAD

**Issue by raist-** [svaarala/duktape#2278] opened 2020-04-20 19:36 UTC
Hi, I am trying to sandbox our usage of Duktape to cap memory usage and also avoid process crashes. In doing so, I am wrapping most Duktape calls in safe calls and pass in custom memory allocation methods. One thing I've run into is that there are some amounts of allocs required when surfacing an alloc error to our safe call handler. This can trigger an infinite loop of allocation failures, until Duktape crashes internally. 

I thought this was addressed as part of https://github.com/svaarala/duktape/issues/476 so I upgraded to 2.4.0, which seemed to include https://github.com/svaarala/duktape/pull/2106 but I still see the infinite loop behavior.

It makes sense to me that this happens because you'd pretty much need to guarantee 0 allocs during error surfacing to avoid this. My workaround so far is to detect this scenario in our custom memory allocator and reserve a little bit of our memory cap specifically for this situation. 

I was curious what your thoughts were on how this scenario should be handled and if it might be reasonable to have more of a supported way to handle this? Our logic to detect this is pretty hacky and relies on knowing the # of allocations we reject in a row. 

If it isn't possible to guarantee 0 allocs in the error scenario then I thought it might be nice to have either:
1. Notify the custom allocator that an allocation error has occurred
2. Allow a dedicated error allocator function to be passed in duk_create_heap and be used specifically to support allocations for this kind of Duktape internal error path.

**Comment by svaarala** [comment] 2020-04-22 20:52
So far I've been trying to ensure that it would be possible to propagate out a pre-allocated Error object with no allocations (or at least relying on allocations succeeding). I think this should be doable, although it does involve some difficult trade-offs (such as preallocating resources which are not needed the vast majority of times, thus slowing down execution, etc).

Can you provide a repro case I could look into (privately is OK too)?

There are two things I would like the allocation interface to support (at least):
- Ability for Duktape to signal that allocations are made in the error propagation path. This would allow the allocator to release some allocated resources reserved for this case. The downside with this is that it's hard to know how much reserve is actually needed, and it's often easy to come up with contrived cases where the required reserve could be made arbitrarily large.
- Ability for the allocator to signal to Duktape that an allocation can be satisfied but using a non-optimal allocation (e.g. using a larger allocator chunk than requested). This would allow Duktape to perform some GC rounds and then retry the allocation, so that wasted space in pool allocators could be better minimized.

The first is probably along the lines you proposed, and it may be something that might be pragmatic at least as a backup to an allocation-free error path.

**Comment by raist-** [comment] 2020-04-23 22:03
Yeah, the first one you mentioned is one of the possibilities I had been thinking of. I'm not that familiar with the error path, so it surprises me that you're saying it is pretty easy to make that path require arbitrarily large amounts of memory. What could cause that? Is it related to the stack size at the time that the error occurs?

Would the Duktape logging be helpful for you? I also have logging of how much memory is attempting to be allocated during the error path. I'll need to check internally to see what I can share in terms of the specific repro or try to come up with a different setup to trigger it.

**Comment by svaarala** [comment] 2020-04-23 22:14
When an error is propagated outwards, activations are closed and freed until a catch point. Closing activations without allocations isn't trivial but should be doable (with some trade-offs).

There have been at least two bugs related to this:
- At some point closing an activation would cause a value stack to be resized to a larger size on return. This happened because a value stack could be shrunk on function entry; this is possible because temporary registers of the calling function can be reused, and there may be more of such temporaries than needed by the callee. The fix involves a trade-off where a value stack may be larger than strictly necessary to guard the unwind.
- When closing scopes, one may need to copy values into an object from function registers. This is now preallocated to avoid allocations on unwind. The fix involves a trade-off in both memory and performance because the property slots must be preallocated on function entry.

Both debug logs and alloc sizes might reveal something. In particular, if you can figure out the place in Duktape unwind code where the allocations happen, it may be enough to figure out the cause.

**Comment by raist-** [comment] 2020-04-24 21:02
I'm not familiar with the term "activations" in this context. Are you referring to cleaning up the active JS callstack?

Here is the callstack, paused at the point of allocation failure in Duktape:
[alloc-loop-stack.txt](https://github.com/svaarala/duktape/files/4531507/alloc-loop-stack.txt)

Seems like some sort of duk_hobject_alloc is occurring as part of pushing the error object?

Here are the logs, where you can see it is repeatedly trying to have us allocate 168 bytes:
[alloc-loop-logs.txt](https://github.com/svaarala/duktape/files/4531487/alloc-loop-logs.txt)

**Comment by svaarala** [comment] 2020-04-24 22:10
Thanks!

At first glance it seems that:
- An out-of-memory error is encountered
- The error handling code (duk_err_create_and_throw()) tries to create an error object.
- That ultimately fails and duk_err_create_and_throw() is called recursively. It then tries to create another error (instead of using the pre-allocated error object). There is an attempt to protect against this by detecting "error when creating an error" (https://github.com/svaarala/duktape/blob/master/src-input/duk_error_throw.c#L83-L118).

Looking at the call stack the two nested error creation call stack entries are separated by an object compaction attempt. This may explain why the protection actually fails:
- When an object compaction attempt happens, we try to create an error but detect the "error when creating an error" condition. It causes a pre-allocated "DoubleError" to be thrown instead from inside the compaction attempt. This throw path then clears the `thr->heap->creating_error` flag because the error was successfully handled. Finally, the compact attempt call site is protected which ignores the error silently instead of propagating it out of the original error call site (which breaks an assumption in the duk_err_create_and_throw()).
- When a new allocation happens (e.g. trying to compact another object), the flag is actually cleared and we try to create an actual error leading to actual nested attempt to create an error object.

This is incorrect, but I'm not 100% sure at this point why it causes a crash. But it's enough to formulate a fix. A few possibilities:
1. Avoid compaction (and finalization) when creating errors because the protected call used for a compaction attempt interferes with the error throwing approach.
2. Handle compaction without a protected call, i.e. use trial allocations which are handled with setjmp/longjmp (something needs to be for finalizers separately).
3. Change the `creating_error` flag into a counter and nest it properly.
4. Save and restore `creating_error` when doing a mark-and-sweep (or for individual compaction attempts) so that `creating_error` remains set when the error object allocation fails.

If you wanted to test this theory, you could disable object compaction and finalization in mark-and-sweep manually and see if it fixes the issue. Something like:
```
diff --git a/src-input/duk_heap_markandsweep.c b/src-input/duk_heap_markandsweep.c
index fc4f224d..d4a98982 100644
--- a/src-input/duk_heap_markandsweep.c
+++ b/src-input/duk_heap_markandsweep.c
@@ -1366,15 +1366,17 @@ DUK_INTERNAL void duk_heap_mark_and_sweep(duk_heap *heap, duk_small_uint_t flags
         *  interfering with error state.
         */
 
+#if 0
        if ((flags & DUK_MS_FLAG_EMERGENCY) &&
            !(flags & DUK_MS_FLAG_NO_OBJECT_COMPACTION)) {
                if (heap->lj.type != DUK_LJ_TYPE_UNKNOWN) {
                        DUK_D(DUK_DPRINT("lj.type (%ld) not DUK_LJ_TYPE_UNKNOWN, skip object compaction", (long) heap->lj.type));
                } else {
                        DUK_D(DUK_DPRINT("object compaction"));
                        duk__compact_objects(heap);
                }
        }
+#endif
 
        /*
         *  String table resize check.
@@ -1473,10 +1475,12 @@ DUK_INTERNAL void duk_heap_mark_and_sweep(duk_heap *heap, duk_small_uint_t flags
         *  XXX: avoid finalizer execution when doing emergency GC?
         */
 
+#if 0
 #if defined(DUK_USE_FINALIZER_SUPPORT)
        /* Attempt to process finalize_list, pf_prevent_count check
         * is inside the target.
         */
        duk_heap_process_finalize_list(heap);
 #endif  /* DUK_USE_FINALIZER_SUPPORT */
+#endif
 }
```

This is not a fix, but would maybe help verify if the above is correct.

**Comment by svaarala** [comment] 2020-04-24 22:53
I tried to write a repro case based on the above theory. It's a little tricky because there are different kinds of allocations within the error creation and they have different side effect protections. For example, if the out-of-memory happens when allocating the error object itself, it will trigger the issue, but if it happens when allocating or resizing the error object's property table, there's protection against not running compaction there (it's needed so the object is not resized recursively) and the issue won't trigger.

I managed to reproduce the issue (or something similar) with a few tries. I'll add it to the testcases, but it's probably going to be fragile in that e.g. changing the `duk-low` pool sizes may then avoid triggering the issue.

Here's the repro:
```js
function test() {
    var obj = {};
    var count = 0;
    while (true) {
        print(count++);
        obj = { ref1: obj, ref2: obj };
    }
}
try {
    test();
} catch (e) {
    print(e);
}
```

It fails with a seemingly infinite loop with `duk-low` after ~1270 loops. With the `#if 0` hack above it exits cleanly with:
```
1262
1263
Error: 1
```

Where the error number is just a plain Error.

I'm not sure if this is exactly the issue you encountered, but the `#if 0` hack test should give an indication of that.

**Comment by svaarala** [comment] 2020-04-24 23:19
Regarding fixes:
> Save and restore creating_error when doing a mark-and-sweep (or for individual compaction attempts) so that creating_error remains set when the error object allocation fails.

This seems straightforward and fixes the issue without limiting mark-and-sweep opportunities for out-of-memory situations. I'll open a pull for this (or some other fix) once we've verified the above hack test fixes your concrete issue.

**Comment by svaarala** [comment] 2020-04-25 23:07
> I'm not that familiar with the error path, so it surprises me that you're saying it is pretty easy to make that path require arbitrarily large amounts of memory. What could cause that?

For example, when activations (script call stack entries) are unwound, sometimes register values need to be copied to a closed environment record. One can add (in essence) arbitrarily many local variables to a function, thus increasing the size of the environment record as much as desired.

A similar issue happens for the value stack if one allows the value stack to shrink on a function call (rather than treating the value stack as "extend only" when going deeper into calls).

**Comment by raist-** [comment] 2020-04-27 21:36
Thanks for the explanation and code to test with! I was able to try it locally, and you're right. That did prevent the infinite loop I was seeing. Instead, it started erroring out with the following:
ErrorCode: 1
ErrorType: DoubleError: error in error handling

Even with this fix, it sounds like this is best effort handling of these situations, but in the end we should always have some fallback behavior by our custom memory allocator in case a different type of situation like this arises?

**Comment by svaarala** [comment] 2020-04-27 21:41
> Even with this fix, it sounds like this is best effort handling of these situations, but in the end we should always have some fallback behavior by our custom memory allocator in case a different type of situation like this arises?

The effort at least at present is 100% handling of these situations, i.e. the error path should not rely on a single allocation succeeding. Without this there is no way for the sandboxing application to handle these cases correctly as it's very difficult to establish a safe value for a memory reserve.

But because it's quite easy to miss something when trying to handle the error path 100% correctly, having some fallback behavior may be a practical approach.

**Comment by svaarala** [comment] 2020-04-27 21:47
@raist- Could you verify that #2290 fix the issue for you?

**Comment by raist-** [comment] 2020-04-27 22:03
That fix is working for me. Thanks!
Could we discuss the possibility of communicating alloc error path information to the custom memory allocator? Would you prefer that discussion in a separate issue?

**Comment by svaarala** [comment] 2020-04-27 22:06
Sure, such a change would now be possible in master as incompatible changes can be made. A separate issue would be better for that discussion I think.

**Comment by svaarala** [comment] 2020-04-27 22:10
Opened https://github.com/svaarala/duktape/issues/2291.

**Comment by svaarala** [comment] 2020-04-27 22:20
@raist- Thanks for reporting the issue! :+1:

**Closed** 2020-04-27 22:19 UTC
Labels: bug, sandboxing
