### ISSUE TITLE
assertion failed: (duk_uint8_t *) thr->valstack + regbase_byteoff + sizeof(duk_tval) * regnum < (duk_uint8_t *) thr->valstack_top in duk_js_close_environment_record

### ISSUE THREAD

**Issue by renatahodovan** [svaarala/duktape#2022] opened 2018-12-30 22:46 UTC
###### Duktape version:

```
Checked revision: b062b50a
Build command: make dukd-low
```

###### OS:

```
Ubuntu 18.04, x86_64
```

###### Test case:

```javascript
function test ( ) { 
    try { 
        test(); 
    } catch ( x ) { 
        TypeError.stack
    } 
    var i; 
    var f = eval( f ); 
} 

test(); 
```

###### Backtrace:

```
Program received signal SIGABRT, Aborted.
0xf7fd5059 in __kernel_vsyscall ()
#0  0xf7fd5059 in __kernel_vsyscall ()
#1  0xf7de0832 in raise () from /lib/i386-linux-gnu/libc.so.6
#2  0xf7de1cc1 in abort () from /lib/i386-linux-gnu/libc.so.6
#3  0x565c8336 in duk_default_fatal_handler.lto_priv.138 (udata=0x0, 
    msg=0x565e0a64 "assertion failed: (duk_uint8_t *) thr->valstack + regbase_byteoff + sizeof(duk_tval) * regnum < (duk_uint8_t *) thr->valstack_top (duk_js_var.c:681)") at duk_error_macros.c:145
#4  0x56567b89 in duk_js_close_environment_record.lto_priv.298 (thr=0xf7fad418, env=0xf7faaacc) at duk_js_var.c:681
#5  0x56570c41 in duk__activation_unwind_nofree_norz (thr=0xf7fad418) at duk_hthread_stacks.c:280
#6  0x56570cfb in duk_hthread_activation_unwind_norz.lto_priv.260 (thr=0xf7fad418) at duk_hthread_stacks.c:317
#7  0x5655fe24 in duk__handle_longjmp (thr=0xf7fad418, entry_act=0xf7fa4064) at duk_js_executor.c:1383
#8  0x56561359 in duk__handle_executor_error (heap=0xf7fb3610, entry_act=0xf7fa4064, entry_call_recursion_depth=2, entry_jmpbuf_ptr=0xffffce30) at duk_js_executor.c:2839
#9  0x565616ad in duk_js_execute_bytecode.lto_priv.283 (exec_thr=0xf7fad418) at duk_js_executor.c:2934
#10 0x56574143 in duk__handle_call_raw (thr=0xf7fad418, idx_func=3, call_flags=0) at duk_js_call.c:2203
#11 0x565748e3 in duk_handle_call_unprotected.lto_priv.254 (thr=0xf7fad418, idx_func=3, call_flags=0) at duk_js_call.c:2385
#12 0x565ca3fd in duk_call_method (thr=0xf7fad418, nargs=0) at duk_api_call.c:152
#13 0x5655a458 in wrapped_compile_execute (ctx=0xf7fad418, udata=0x0) at examples/cmdline/duk_cmdline.c:301
#14 0x56574bab in duk__handle_safe_call_inner (thr=0xf7fad418, func=0x5655a1db <wrapped_compile_execute>, udata=0x0, entry_valstack_bottom_byteoff=0, entry_callstack_top=0, entry_curr_thread=0x0, 
    entry_thread_state=1 '\001', idx_retbase=0, num_stack_rets=1) at duk_js_call.c:2438
#15 0x565756a4 in duk_handle_safe_call.lto_priv.479 (thr=0xf7fad418, func=0x5655a1db <wrapped_compile_execute>, udata=0x0, num_stack_args=4, num_stack_rets=1) at duk_js_call.c:2683
#16 0x565cb3af in duk_safe_call (thr=0xf7fad418, func=0x5655a1db <wrapped_compile_execute>, udata=0x0, nargs=4, nrets=1) at duk_api_call.c:320
#17 0x5655a657 in handle_fh (ctx=0xf7fad418, f=0x566bd160, filename=0xffffd396 "test.js", bytecode_filename=0x0) at examples/cmdline/duk_cmdline.c:632
#18 0x5655a831 in handle_file (ctx=0xf7fad418, filename=0xffffd396 "test.js", bytecode_filename=0x0) at examples/cmdline/duk_cmdline.c:691
#19 0x5655b3df in main (argc=2, argv=0xffffd1e4) at examples/cmdline/duk_cmdline.c:1465
```

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/) with [grammarinator](https://github.com/renatahodovan/grammarinator). </sup>

**Comment by svaarala** [comment] 2018-12-30 22:59
Thanks @renatahodovan, I'll check this out.

**Comment by svaarala** [comment] 2019-06-24 22:28
The root cause for this seems to be:
- Bytecode executor is executing code when it encounters an error (here, a RangeError for a callstack limit or an out-of-memory error).
- Bytecode executor longjmp handling locates the activation with an active catch clause.
- The longjmp handler, still executing in "error handling mode", tries to setup the dynamic scope for the catch clause (i.e. the `e` binding for `catch (e) { ... }`).
- If that allocation fails, it causes retries after GC, and ultimately an emergency GC.
- The emergency GC will attempt to compact objects, leading to a safe call inside error handling, which is not allowed.
- If that is fixed by skipping compaction in this case (which is easy), it won't solve the problem because the allocation then fails, leading to an out-of-memory error within a RangeError, with similar consequences.

This is a known leftover for the error unwind path which should ideally be memory allocation free.

A short term fix would be, for example, to handle an ECMAScript catch clause in two parts:
- Part 1: just push the error value on the value stack (preallocated, so should always work without allocation), clear error handling state, and flag "delayed catch setup". The catcher flag for "catch active" is also cleared to ensure we never enter a forever loop.
- Part 2: when a new setjmp() has been issued, detect delayed catch setup, and finish the catch scope setup outside of "error handling state". If *this* fails, the error bubbles out further (the catcher is no longer active for catching).

I tested this approach and it seems to work as expected.

A better long term solution would be to refactor error handling in general so that:
- Error state would always be pushed on the value stack rather than a heap-based state. This then allows, for example, nested error handling, as long as the initial push is free of allocations.

This still doesn't make error handling easy, e.g. scopes still need preallocation so that they can be reliably closed. But it would reduce global assumptions in error handling, allow nested errors to some degree, etc.

**Closed** 2019-07-05 20:23 UTC
Labels: bug
