### ISSUE TITLE
Reference Error line number?

### ISSUE THREAD

**Issue by dzzie** [svaarala/duktape#253] opened 2015-08-05 12:54 UTC
Is it possible to get a line number included in reference error messages?

ex:
```c
print(window.location)
```

output:
ReferenceError: identifier 'window' undefined

desired:
ReferenceError: identifier 'window' undefined (line 1)

**Comment by svaarala** [comment] 2015-08-05 13:06
Error messages will actually include a lineNumber property but it's not part of the message. Technically the `message` argument given to, say, `new Error("my message")` is required to be assigned to the error object as is.

You can implement a Duktape-specific solution with Duktape.errCreate though:

```js
Duktape.errCreate = function (err) {
    try {
        if (typeof err === 'object' &&
            typeof err.message !== 'undefined' &&
            typeof err.lineNumber === 'number') {
            err.message = err.message + ' (line ' + err.lineNumber + ')';
        }
    } catch (e) {
        // ignore; for cases such as where "message" is not writable etc
    }
    return err;
}

try {
    window.location = 'foo';
} catch (e) {
    print(e);
}
```

Running this you'd get something like:

```
ReferenceError: identifier 'window' undefined (line 15)
```

**Comment by fatcerberus** [comment] 2015-08-05 14:31
You did you get "identifier undefined"?  Usually I get a useless "invalid base value" error...

**Comment by svaarala** [comment] 2015-08-05 14:33
Invalid base value is related to property lookup, e.g. you lookup `foo.bar` where `foo` is undefined or null.

**Comment by svaarala** [comment] 2015-08-05 14:35
I also don't really understand why the "invalid base value" error is useless?

**Comment by fatcerberus** [comment] 2015-08-05 14:39
It's useless because it doesn't tell you the name of the object the lookup was attempted on, and the line number alone often isn't enough to pin down the cause, e.g. in a function call with several arguments where each one involves a property lookup.  I actually posted an issue regarding this a while ago...

**Comment by svaarala** [comment] 2015-08-05 14:41
Duktape doesn't know the "name" at the lookup point. The base value has been loaded into a VM register so it's just a plain value it's operating on.

The error message could include the key (coerced to a string, with potential side effects) but that's actually a very bad idea for security critical environments because the key may be a security sensitive value. I work in the payment card industry and if they key were a card number it'd be a issue if it could end up in an error message or traceback. There could be an option for including the key but it should be possible to disable.

**Comment by fatcerberus** [comment] 2015-08-05 14:48
Not sure how the key would be traceable back to actual data, wouldn't it just be a hash of an identifier or somesuch?  I'd imagine the *contents* of the object would be more sensitive security-wise, no?

For what it's worth SpiderMonkey does show the object name in this case ("'foo' has no properties").  I guess Duktape's parser must be structured differently that it "forgets" the object name by the time the lookup is done...

**Comment by svaarala** [comment] 2015-08-05 14:50
Why couldn't a key be a card number -- for instance, if I had an object tracking metadata related to recently encountered cards?

Comparing to V8, it includes the key but also "forgets" the base value:

```
> a = null
null
> a.foo
TypeError: Cannot read property 'foo' of null
    at repl:1:2
    at REPLServer.defaultEval (repl.js:132:27)
    at bound (domain.js:254:14)
    at REPLServer.runBound [as eval] (domain.js:267:12)
    at REPLServer.<anonymous> (repl.js:279:12)
    at REPLServer.emit (events.js:107:17)
    at REPLServer.Interface._onLine (readline.js:214:10)
    at REPLServer.Interface._line (readline.js:553:8)
    at REPLServer.Interface._ttyWrite (readline.js:830:14)
    at ReadStream.onkeypress (readline.js:109:10)
```

**Comment by svaarala** [comment] 2015-08-05 14:52
Also note that there may not even be a named base value, e.g. in `("foo" + "bar")[5]`.

**Comment by fatcerberus** [comment] 2015-08-05 14:58
Oh, I thought by key you meant a hash of the name, not the property name itself.

To be fair, if the code is minified most of the keys will become meaningless anyway, barring edge cases like `eval`.  And anybody storing card numbers in plaintext (as object property names) is asking for trouble anyway. :wink:  But I guess I do see the security implications in general.  Keep in mind of course that we're talking about JS which is traditionally kept in source form, so if someone _really_ wanted to know the name of the key they'd just have to get access to the source.

All that said, an option to display the key would be nice.  In my particular case I'm writing a game engine, so implementation details are a lot less sensitive.

**Comment by svaarala** [comment] 2015-08-05 15:05
I didn't mean a card number would be a literal in the source file - it would normally be dynamic data that you *had* to deal with if you handled card data to begin with. (It's actually quite a complicated topic and best practice is to encrypt the numbers in native code etc, but it's not really relevant to this discussion.)

And sure, if I were reviewing card handling code, I'd certainly recommend not using sensitive data as property keys (or values for that matter, they should be encrypted in native code if possible). But is it good practice for an engine to make that assumption *for all code*? Not in my opinion. As a similar issue, it might also be very useful to include local variable names and/or values in tracebacks but it would be a bad idea (at least as a default) for similar reasons.

One approach might be to make inclusion of the key in the error message the default, but add a guide section for security sensitive environments and list the features to turn off for these environments.

**Comment by fatcerberus** [comment] 2015-08-05 15:15
Do keep in mind that when *native code* crashes, it generally includes a core dump generated by the operating system of the program's entire working set.  A single property key is small potatoes by comparison. :)

**Comment by svaarala** [comment] 2015-08-05 15:17
The difference is that an error message might be sent out in a log file etc. A core file would not.

**Comment by fatcerberus** [comment] 2015-08-05 15:20
True.  Anyway, I said my piece, so do what you will. :)

**Comment by svaarala** [comment] 2015-08-05 15:47
To be clear, I don't object to adding the key to a property lookup failure error messages (it's been a low priority issue for a while now). But I don't agree with the argument that keys would never be security sensitive, so this change does matter to some users (me included :-). I'd at least need an option to turn that behavior off.

There's no firm default policy now for whether defaults should favor security or convenience and it'd be nice for that default to be consistent. For footprint/performance the default is performance now and the low memory documentation tells what to do to bring the footprint down (which works pretty well I think).

Since filenames, line numbers, and tracebacks are all available by default (all of which are potentially frowned upon in security audits), perhaps convenience should be the default. The documentation should then be clear what to do if you're working with a security sensitive environment.

**Comment by svaarala** [comment] 2015-08-05 16:13
Anyway, related to the original issue, another approach to adding a line number to the message would be to override `Error.prototype.toString()` so that the result would combine `.name`, `.message`, and `.lineNumber` of the error.

But trying this out, I noticed a small gotcha with this: `.fileName` and `.lineNumber` are accessor properties which figure out their value dynamically based on the internal traceback data property. That's fine by itself, but they're implemented a shared helper which does a `toString()` coercion for the error (even when it's not needed) - leading to an infinite loop. Right now you'd need to replace the accessors too.

Opened #254.

**Comment by dzzie** [comment] 2015-08-05 16:22
The Duktape.errCreate code did the trick. I will add that to my engine init so I always have an accessible line number to highlight in the UI when duk_peval returns an error code. I was just thinking that the following duk_safe_to_string(ctx, -1) on error would have had always had a line number embedded. This works though. Thanks

Since the conversation branced into other things I will let you guys close this.

**Comment by svaarala** [comment] 2015-08-05 16:28
If you have a single place where you'd need to log that error, you could just replace `duk_safe_to_string()` with your own function which read `.lineNumber` etc. You wouldn't need to use `Duktape.errCreate` then which would probably be preferable.

**Closed by svaarala** 2015-08-05 16:28 UTC
Labels: question

**Comment by dzzie** [comment] 2015-08-06 09:26
I guess I found better wording just for completeness. In the following code snippet:

```C
        rv = duk_peval_file(ctx, pth); //0 = success
	if(rv != 0){
		setLastString(duk_safe_to_string(ctx, -1)); //error message..
	}
```

Some error messages like syntax error will include a (line xx) section of the message, while some like reference error will not. I wasnt sure if it was meant to be standardized here.

**Comment by svaarala** [comment] 2015-08-06 09:39
Whatever code creates a new Error can include a line or offset in the error message; syntax errors and parse errors do that for convenience. But as a general thing, it might break stuff if Duktape were to automatically modify the message argument to `new Error(message)` thrown by all (also user) code. It would certainly be a compliance issue, but might actually break something obscure somewhere.

Duktape does add `.fileName` and `.lineNumber` because extra properties are not forbidden (and these two are actually often expected while they're not part of the standard).

**Comment by svaarala** [comment] 2015-08-07 10:25
@dzzie The testcase for #254 illustrates another option for getting linenumbers to error messages (or rather, when string coercing an error) which now works in master:

https://github.com/svaarala/duktape/blob/f16f2bcca3a52a8872378ab5277ef9670796cc63/tests/ecmascript/test-bug-error-tostring-replacement-gh254.js#L26-L37

**Comment by dzzie** [comment] 2015-08-07 16:34
great thanks
